# When triggered, it creates a new branch off of major_debug_draft 
#and a new file to write the chapter. 

name: Minor updates for a chapter

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      filename:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Name of the chapter file (without.md) EX: Chapter_1'
        # Default value if no value is explicitly provided
        default: 'Untitled'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  add_chapter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Accesses the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: major_debug_draft  # Ensure 'dev' is checked out
          fetch-depth: 0  # Fetch all branches
    # Sets up Actions as the commit author
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
    #Create a new branch
      - name: Create new branch
        run: git checkout -b minimal-update-${{ github.event.inputs.filename }} minimal_debug_draft
    #Push the new branch from virtual machine to remote repository
      - name: Push new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin minimal-update-${{ github.event.inputs.filename }}
